### ISSUE TITLE
NISTtheDocs2Death renamed to Docs4NIST

### ISSUE THREAD

**Issue by guyer** [ianhbell/teqp-docs#1]
OISM are humorless trolls. The action is now at https://github.com/usnistgov/Docs4NIST.

I see you're using your own fork, so I'm not proposing a PR.

**Comment by ianhbell** [comment]
Got it - I will rename my fork too and update my remote

**Comment by ianhbell** [comment]
I got it all sorted, the only surprise was that I also had to rename the base image in the Dockerfile
